- name: copy wp-config-sample.php 
  become: true
  command: cp /var/www/{{ item }}/wp-config-sample.php /var/www/{{ item }}/wp-config.php
  with_items: 
     - "{{ client_list_w1 }}"
     - "{{ client_list_w2 }}"

- name: db name
  become: true
  lineinfile:
    path: /var/www/{{ item }}/wp-config.php
    regexp: '^database_name_here'
    line: define('DB_NAME', '{{ item }}_db')
  with_items: 
     - "{{ client_list_w1 }}"
     - "{{ client_list_w2 }}"
  
- name: db user
  become: true
  lineinfile:
    path: /var/www/{{ item }}/wp-config.php
    regexp: '^username_here'
    line: define('DB_USER', 'itesciadmin')
  with_items: 
     - "{{ client_list_w1 }}"
     #- "{{ client_list_w2 }}"

- name: db password
  become: true
  lineinfile:
    path: /var/www/{{ item }}/wp-config.php
    regexp: '^password_here'
    line: define('DB_PASSWORD', 'itescia')
  with_items: 
     - "{{ client_list_w1 }}"
     #- "{{ client_list_w2 }}"

- name: db host
  become: true
  lineinfile:
    path: /var/www/{{ item }}/wp-config.php
    regexp: '^DB_HOST'
    line: define('DB_HOST', '10.0.0.141')
  with_items: 
     - "{{ client_list_w1 }}"
     #- "{{ client_list_w2 }}"
